name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Install clang-format
      run: sudo apt-get install clang-format
     
    - name: Run clang-format
      run: clang-format -i src/*.cpp include/*.h test/*.cpp
      
    - name: Install cppcheck
      run: sudo apt-get install cppcheck
    
    - name: Run cppcheck
      run: cppcheck --enable=all --inconclusive --std=c++17 src

    - name: Install MPI
      run: sudo apt-get install libmpich-dev

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build

    - name: Create a container image
      run: sudo singularity build --sandbox singularity_container/ Singularity.def
